import os
import re
import logging
from typing import List, Dict, Any

import pypdf
from langchain_groq import ChatGroq
from langchain_core.prompts import PromptTemplate

from app.core.config import settings

logger = logging.getLogger(__name__)


class PurePythonDocStore:
    def __init__(self):
        self.chunks: List[Dict[str, Any]] = []

    def add_texts(self, texts: List[str], metadatas: List[Dict[str, Any]] = None):
        for i, t in enumerate(texts):
            meta = metadatas[i] if metadatas and i < len(metadatas) else {}
            words = set(re.findall(r'\w+', t.lower()))
            self.chunks.append({
                "content": t,
                "metadata": meta,
                "words": words
            })

    def search(self, query: str, top_k: int = 3) -> List[str]:
        if not self.chunks:
            return []
        q_words = set(re.findall(r'\w+', query.lower()))
        if not q_words:
            return [c["content"] for c in self.chunks[:top_k]]

        scored = []
        for c in self.chunks:
            overlap = len(q_words.intersection(c["words"]))
            scored.append((overlap, c["content"]))

        scored.sort(key=lambda x: x[0], reverse=True)
        return [content for score, content in scored[:top_k]]


class RagService:
    def __init__(self):
        self.pdf_dir = os.path.join(os.getcwd(), "pdf_data")
        self.doc_store = PurePythonDocStore()
        self._initialized = False

    def initialize_knowledge_base(self):
        """Called on startup. Ingests PDFs into in-memory document store."""
        if self._initialized:
            return

        if not os.path.exists(self.pdf_dir):
            os.makedirs(self.pdf_dir, exist_ok=True)
            logger.warning(f"No PDF found in {self.pdf_dir}.")
            self._initialized = True
            return

        pdf_files = [f for f in os.listdir(self.pdf_dir) if f.endswith(".pdf")]
        if not pdf_files:
            logger.warning(f"No PDF found in {self.pdf_dir}.")
            self._initialized = True
            return

        documents = []
        for pdf_file in pdf_files:
            file_path = os.path.join(self.pdf_dir, pdf_file)
            try:
                reader = pypdf.PdfReader(file_path)
                for page_idx, page in enumerate(reader.pages):
                    text = page.extract_text() or ""
                    if text.strip():
                        documents.append({"text": text, "source": pdf_file, "page": page_idx})
            except Exception as e:
                logger.error(f"Error reading PDF {pdf_file}: {e}")

        # Chunk documents
        chunk_size = 800
        chunk_overlap = 100
        chunks = []
        metas = []
        for doc in documents:
            text = doc["text"]
            start = 0
            while start < len(text):
                end = min(start + chunk_size, len(text))
                chunks.append(text[start:end])
                metas.append({"source": doc["source"], "page": doc["page"]})
                if end == len(text):
                    break
                start += chunk_size - chunk_overlap

        self.doc_store.add_texts(chunks, metas)
        self._initialized = True
        logger.info(f"Ingested {len(chunks)} document chunks for AI policy retrieval.")

    def _strip_think_tags(self, text: str) -> str:
        """Removes reasoning tags if generated by models."""
        cleaned = re.sub(r"<think>.*?(?:</think>|$)", "", text, flags=re.DOTALL).strip()
        return cleaned or "I am here to assist with your flight booking and airline policies."

    async def chat(self, user_query: str) -> str:
        if not settings.GROQ_API_KEY:
            return "Error: GROQ_API_KEY is not configured."

        if not self._initialized:
            self.initialize_knowledge_base()

        llm = ChatGroq(
            api_key=settings.GROQ_API_KEY,
            model_name="openai/gpt-oss-20b",
            temperature=0,
            max_tokens=1000
        )

        # Step 1: Intent Classification
        intent_prompt = PromptTemplate.from_template(
            "You are an intent classifier for an airline chatbot. "
            "Classify the following user input into exactly one of these categories: "
            "GREETING (for hellos, hi, thank you, goodbye, etc.) or RAG_QUERY (for questions about airline rules, flights, policies, etc.). "
            "Respond with ONLY the category name. No extra words. DO NOT use <think> tags.\n"
            "User input: {query}\n"
            "Category:"
        )
        intent_chain = intent_prompt | llm
        try:
            intent_result = await intent_chain.ainvoke({"query": user_query})
            intent_text = intent_result.content.upper()
        except Exception as e:
            logger.error(f"Intent classification error: {e}")
            intent_text = "RAG_QUERY"

        if "GREETING" in intent_text or "THANKS" in intent_text:
            casual_prompt = PromptTemplate.from_template(
                "You are a helpful customer support agent for SkyFlow Airlines. "
                "The user said: '{query}'. "
                "Respond politely and concisely (1-2 sentences max). DO NOT use <think> tags."
            )
            casual_chain = casual_prompt | llm
            casual_res = await casual_chain.ainvoke({"query": user_query})
            return self._strip_think_tags(casual_res.content)

        # Step 2: Context-Aware QA
        matched_docs = self.doc_store.search(user_query, top_k=3)
        context = "\n\n".join(matched_docs) if matched_docs else "Standard airline policies apply."

        qa_prompt = PromptTemplate.from_template(
            "You are an AI travel concierge for SkyFlow Airlines. "
            "Use the following policy context to answer the user query accurately and concisely:\n\n"
            "Context:\n{context}\n\n"
            "User Question:\n{query}\n\n"
            "Answer strictly and concisely (1 to 2 sentences max, no fluff, no think tags):"
        )
        qa_chain = qa_prompt | llm
        qa_res = await qa_chain.ainvoke({"context": context, "query": user_query})
        return self._strip_think_tags(qa_res.content)


rag_service = RagService()
