"""add_approval_fields_to_audit_log

Revision ID: 06a88cbc5980
Revises: eee9eff83e60
Create Date: 2026-09-08 03:38:09.125712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06a88cbc5980'
down_revision: Union[str, None] = 'eee9eff83e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('requires_approval', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('audit_logs', sa.Column('approval_status', sa.Enum('AUTO_APPROVED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='approval_status_enum', native_enum=False), server_default='AUTO_APPROVED', nullable=False))
    op.add_column('audit_logs', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'audit_logs', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'approved_by')
    op.drop_column('audit_logs', 'approval_status')
    op.drop_column('audit_logs', 'requires_approval')
    # ### end Alembic commands ###
