"""multi_leg_pnr

Revision ID: eee9eff83e60
Revises: 
Create Date: 2026-09-06 21:29:05.874684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eee9eff83e60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_booking_reference'), table_name='bookings')
    op.create_index(op.f('ix_bookings_booking_reference'), 'bookings', ['booking_reference'], unique=False)
    op.create_index('uq_booking_reference_flight', 'bookings', ['booking_reference', 'flight_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_booking_reference_flight', table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_reference'), table_name='bookings')
    op.create_index(op.f('ix_bookings_booking_reference'), 'bookings', ['booking_reference'], unique=True)
    # ### end Alembic commands ###
